### ISSUE TITLE
Just curious that which desktop manager you used in the preview video in README.md?

### ISSUE THREAD

**Issue by nyngwang** [kwkarlwang/bufresize.nvim#7]
As title. I'm asking about these 7 desktops:

<img src="https://user-images.githubusercontent.com/24765272/145765145-51d26959-04ea-4ff9-9c51-55a0b7aec6f1.png" width="500">

**Comment by kwkarlwang** [comment]
It is [Spaceman](https://github.com/Jaysce/Spaceman), works perfect with yabai!
